version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    env_file:
      - variables.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
